# generated from potential_field_control/env-hooks/reactive_control.sh.in

ament_prepend_unique_value GAZEBO_MODEL_PATH "$AMENT_CURRENT_PREFIX/share/potential_field_control/models"
ament_prepend_unique_value GAZEBO_RESOURCE_PATH "$AMENT_CURRENT_PREFIX/share/potential_field_control/worlds"
